baseURL: https://dnjp.github.io
languageCode: en-us
title: Daniel Posthuma
theme: "PaperMod"

params:
  # homeInfoParams:
  #   Title: Daniel Posthuma
  #   #   Content: This is something shows in your homepage.
  #   Content: 👋 I’m Daniel - a software engineer primarily interested in [distributed systems](https://en.wikipedia.org/wiki/Distributed_computing), [decentralized finance](https://en.wikipedia.org/wiki/Decentralized_finance), and [algorithmic trading]({{< ref "/pages/Learn Trading" >}}). I'm currently building high performance, low latency bidding systems for [Martin](https://martin.ai/) that support billions of requests per day, most of which are written in [Go]({{< ref "/pages/Go" >}}).

  profileMode:
    enabled: true
    # title: "<Title>" # optional default will be site title
    subtitle: 👋 I’m Daniel - a software engineer primarily interested in [distributed systems](https://en.wikipedia.org/wiki/Distributed_computing), [decentralized finance](https://en.wikipedia.org/wiki/Decentralized_finance), and [algorithmic trading]({{< ref "/pages/Learn Trading" >}}). I'm currently building high performance, low latency bidding systems for [Martin](https://martin.ai/) that support billions of requests per day, most of which are written in [Go]({{< ref "/pages/Go" >}}).
    imageUrl: "https://pbs.twimg.com/profile_images/1545390972212846592/kupeZXy8_400x400.jpg" # optional
    # imageTitle: "<title of image as alt>" # optional
    imageWidth: 120 # custom size
    imageHeight: 120 # custom size
    buttons:
      - name: Blog
        url: "/blog"
      # - name: Github
      #   url: "https://github.com/"

  socialIcons: # optional
    - name: "github"
      url: "https://github.com/dnjp"
    # - name: "youtube"
    #   url: "https://www.youtube.com/channel/XXX"
    - name: "twitter"
      url: "https://twitter.com/_dnjp"
    # - name: "kofi"
    #   url: "https://buymeacoffee.com/XXX"
    # - name: "rss"
    #   url: "https://XXX.github.io/index.xml"
  ShowReadingTime: true
  author: "Daniel Posthuma"
  contact: "hello@danieljames.life"
  feedlinks: true
  copyright: "<!--Creative Commons License-->This site is licensed under a [Creative Commons Attribution-ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-sa/4.0/).<!--/Creative Commons License-->"
  mobileMenu: true

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary
  section:
    - HTML
    - RSS
    - JSON

menu:
  main:
    # - identifier: categories
    #   name: Categories
    #   url: /categories/
    #   weight: 10
    # - identifier: tags
    #   name: Tags
    #   url: /tags/
    #   weight: 20
    # - identifier: search
    #   name: Search
    #   url: /search/
    #   weight: 20
    - identifier: blog
      name: Blog
      url: /blog/
      weight: 20
